# Generated by Django 5.2.17 on 2026-08-31 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_label', models.CharField(max_length=255)),
                ('current_lat', models.FloatField()),
                ('current_lon', models.FloatField()),
                ('pickup_label', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lon', models.FloatField()),
                ('dropoff_label', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lon', models.FloatField()),
                ('cycle_used_hours', models.FloatField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('total_miles', models.FloatField()),
                ('total_drive_hours', models.FloatField()),
                ('total_on_duty_hours', models.FloatField()),
                ('cycle_hours_at_end', models.FloatField()),
                ('route_geometry', models.JSONField(default=list)),
                ('legs', models.JSONField(default=list)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='trips_trip_created_44654c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('start', 'Start'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel stop'), ('break', '30-minute break'), ('rest', '10-hour rest'), ('restart', '34-hour restart')], max_length=16)),
                ('label', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=120)),
                ('arrive_at', models.DateTimeField()),
                ('depart_at', models.DateTimeField()),
                ('duration_hours', models.FloatField()),
                ('trip_miles', models.FloatField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(fields=('trip', 'order'), name='unique_stop_order_per_trip')],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('sheet_number', models.PositiveIntegerField()),
                ('total_sheets', models.PositiveIntegerField()),
                ('miles', models.FloatField()),
                ('off_hours', models.FloatField()),
                ('sleeper_hours', models.FloatField()),
                ('driving_hours', models.FloatField()),
                ('on_duty_hours', models.FloatField()),
                ('segments', models.JSONField(default=list)),
                ('remarks', models.JSONField(default=list)),
                ('recap', models.JSONField(default=dict)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip')),
            ],
            options={
                'ordering': ('sheet_number',),
                'constraints': [models.UniqueConstraint(fields=('trip', 'day'), name='unique_log_day_per_trip')],
            },
        ),
    ]
