# Generated by Django 5.2.17 on 2026-08-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_placecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route_is_estimated',
            field=models.BooleanField(default=False),
        ),
    ]
