# Generated by Django 5.2.17 on 2026-09-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_route_is_estimated'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='cycle_hours',
            field=models.FloatField(default=0),
        ),
    ]
