#!/usr/bin/env bash
# Writes backend/.env from prompts. Values are read without echoing and never
# printed, so no secret ends up in your shell history or terminal scrollback.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/backend/.env"

echo "Setting up $ENV_FILE"
echo "Press return to skip a value and keep the local default."
echo

read -rsp "OpenRouteService API key (starts eyJ): " ORS_KEY; echo
read -rsp "Neon DATABASE_URL (postgresql://...): " DB_URL; echo
echo

# Neon's "Copy snippet" can hand you `psql 'postgresql://...'` rather than the
# bare URL. Strip the wrapper and any quotes so either paste works.
DB_URL="$(printf '%s' "$DB_URL" | sed -E "s/^[[:space:]]*psql[[:space:]]+//; s/^['\"]//; s/['\"][[:space:]]*$//; s/[[:space:]]*$//")"
ORS_KEY="$(printf '%s' "$ORS_KEY" | tr -d '[:space:]')"

fail=0
if [ -n "$ORS_KEY" ] && [ "${ORS_KEY#eyJ}" = "$ORS_KEY" ]; then
    echo "  warning: the ORS key does not start with 'eyJ'. HeiGIT keys issued" >&2
    echo "           since 2025 are JWTs. Check you copied the whole value." >&2
fi
if [ -n "$DB_URL" ] && [ "${DB_URL#postgres}" = "$DB_URL" ]; then
    echo "  error: DATABASE_URL should start with postgresql:// or postgres://" >&2
    fail=1
fi
if [ -n "$DB_URL" ] && ! printf '%s' "$DB_URL" | grep -q -- "-pooler"; then
    echo "  warning: that Neon host has no '-pooler' in it. Turn on Connection" >&2
    echo "           pooling in the Neon dialog and copy again." >&2
fi
[ "$fail" -eq 1 ] && { echo "Nothing written."; exit 1; }

SECRET="$(python3 -c 'import secrets; print(secrets.token_urlsafe(50))')"

{
  echo "# Generated by scripts/setup-env.sh. Not committed."
  echo "DJANGO_SECRET_KEY=$SECRET"
  echo "DJANGO_DEBUG=True"
  echo "DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,.onrender.com,.vercel.app"
  echo "CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173"
  echo
  echo "ORS_PROFILE=driving-hgv"
  echo "ORS_BASE_URL=https://api.heigit.org/openrouteservice"
  echo "ORS_GEOCODE_URL=https://api.heigit.org/pelias/v1"
  [ -n "$ORS_KEY" ] && echo "ORS_API_KEY=$ORS_KEY"
  echo
  [ -n "$DB_URL" ] && echo "DATABASE_URL=$DB_URL"
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"

echo "Wrote $ENV_FILE ($(wc -l < "$ENV_FILE" | tr -d ' ') lines, mode 600)."
echo "ORS key:      $([ -n "$ORS_KEY" ] && echo "set (${#ORS_KEY} chars)" || echo "not set - will use estimated distances")"
echo "DATABASE_URL: $([ -n "$DB_URL" ] && echo "set" || echo "not set - will use local SQLite")"
